### ISSUE TITLE
上传图片不太懂怎么用

### ISSUE THREAD

**Issue by glotm** [jsdawn/vue3-tinymce#3]
我是用的是阿里云的oss，富文本上传图片，不知道这些参数怎么填写，能教学一下吗？

![image](https://github.com/jsdawn/vue3-tinymce/assets/69087402/11f41976-77fd-4ade-a0c7-13c52a94b91a)

**Comment by jsdawn** [comment]
xx_url: 上传图片api接口地址；
xx_callback: 接口返回数据，res.url 回填上传成功后的图片url；
xx_param: 接口额外参数
