### ISSUE TITLE
images_file_types 属性为什么不起作用呢？

### ISSUE THREAD

**Issue by bbhxwl** [jsdawn/vue3-tinymce#4]
不支持么？

**Comment by jsdawn** [comment]
支持的，源码中以`getTinymce().init(setting)`的形式注入设置，与tinymce@6的设置同步

**Comment by bbhxwl** [comment]
> 支持的，源码中以`getTinymce().init(setting)`的形式注入设置，与tinymce@6的设置同步


通过setting 的方法，里面我设置了不起作用呢。
<vue3-tinymce
            v-model="model" :setting="setting"/>

**Comment by bbhxwl** [comment]
> 支持的，源码中以`getTinymce().init(setting)`的形式注入设置，与tinymce@6的设置同步

```
 <vue3-tinymce
            v-model="model" :setting="setting"/>
```

**Comment by bbhxwl** [comment]
求指点呢
![image](https://github.com/jsdawn/vue3-tinymce/assets/26525599/45b696eb-368c-4bd3-9285-a06cd317b4c3)
![image](https://github.com/jsdawn/vue3-tinymce/assets/26525599/96ef7b7c-706d-49dc-9688-9f00a034ee4b)
